Don't require `active_storage`
We don't use it and it's causing errors:

```
RuntimeError: Couldn't find Active Storage configuration in /app/config/storage.yml
/app/vendor/bundle/ruby/2.6.0/gems/activestorage-6.1.1/lib/active_storage/engine.rb:121:in `block (2 levels) in <class:Engine>'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/lazy_load_hooks.rb:71:in `class_eval'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/lazy_load_hooks.rb:71:in `block in execute_hook'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/lazy_load_hooks.rb:51:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
/app/vendor/bundle/ruby/2.6.0/gems/activestorage-6.1.1/app/models/active_storage/blob.rb:346:in `<top (required)>'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `block in require'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:299:in `load_dependency'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:332:in `require'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:424:in `block in require_or_load'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:39:in `block in load_interlock'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/dependencies/interlock.rb:13:in `loading'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:39:in `load_interlock'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:402:in `require_or_load'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:375:in `depend_on'
/app/vendor/bundle/ruby/2.6.0/gems/activesupport-6.1.1/lib/active_support/dependencies.rb:288:in `require_dependency'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.1/lib/rails/engine.rb:493:in `block (2 levels) in eager_load!'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.1/lib/rails/engine.rb:492:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.1/lib/rails/engine.rb:492:in `block in eager_load!'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.1/lib/rails/engine.rb:489:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.1/lib/rails/engine.rb:489:in `eager_load!'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.1/lib/rails/engine.rb:358:in `eager_load!'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.1/lib/rails/application/finisher.rb:134:in `each'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.1/lib/rails/application/finisher.rb:134:in `block in <module:Finisher>'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.1/lib/rails/initializable.rb:32:in `instance_exec'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.1/lib/rails/initializable.rb:32:in `run'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each'
/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `call'
/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
/app/vendor/ruby-2.6.5/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.1/lib/rails/initializable.rb:60:in `run_initializers'
/app/vendor/bundle/ruby/2.6.0/gems/railties-6.1.1/lib/rails/application.rb:384:in `initialize!'
/app/config/environment.rb:5:in `<top (required)>'
config.ru:4:in `require'
config.ru:4:in `block in <main>'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `instance_eval'
/app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.3/lib/rack/builder.rb:125:in `initialize'
config.ru:1:in `new'
config.ru:1:in `<main>'
/app/vendor/bundle/ruby/2.6.0/gems/unicorn-5.7.0/lib/unicorn.rb:54:in `eval'
/app/vendor/bundle/ruby/2.6.0/gems/unicorn-5.7.0/lib/unicorn.rb:54:in `block in builder'
/app/vendor/bundle/ruby/2.6.0/gems/unicorn-5.7.0/lib/unicorn/http_server.rb:822:in `build_app!'
/app/vendor/bundle/ruby/2.6.0/gems/unicorn-5.7.0/lib/unicorn/http_server.rb:141:in `start'
/app/vendor/bundle/ruby/2.6.0/gems/unicorn-5.7.0/bin/unicorn:128:in `<top (required)>'
/app/vendor/bundle/ruby/2.6.0/bin/unicorn:23:in `load'
/app/vendor/bundle/ruby/2.6.0/bin/unicorn:23:in `<top (required)>'
```